<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Fee Library_svg svg-signature_pen</name>
   <tag></tag>
   <elementGuidId>690b9207-30da-44d1-abf1-6c2b3d571e14</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.svg.svg-signature_pen</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='pyElementToolbar']/ul/li[9]/a/span[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>svg svg-signature_pen</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pyElementToolbar&quot;)/ul[@class=&quot;tool-list&quot;]/li[@class=&quot;no-repeaters more-options&quot;]/a[@class=&quot;cinder&quot;]/span[@class=&quot;svg svg-signature_pen&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='pyElementToolbar']/ul/li[9]/a/span[2]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[8]/ul/li[9]/a/span[2]</value>
   </webElementXpaths>
</WebElementEntity>
